import { NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase'

export async function GET() {
  const db = supabaseAdmin()

  const [{ data: trades }, { data: reviews }, { data: perf }] = await Promise.all([
    db.from('trades').select('*').eq('status', 'closed').order('closed_at', { ascending: true }),
    db.from('trade_reviews').select('*').order('reviewed_at', { ascending: false }),
    db.from('performance_summary').select('*'),
  ])

  const closed = trades ?? []

  // Equity curve — cumulative P&L
  let cumulative = 0
  const equity = closed.map(t => {
    cumulative += t.pnl_usd ?? 0
    return {
      date:       t.closed_at?.slice(0, 10) ?? '',
      pnl:        Math.round((t.pnl_usd ?? 0) * 100) / 100,
      cumulative: Math.round(cumulative * 100) / 100,
      asset:      t.asset,
      direction:  t.direction,
    }
  })

  // Monthly P&L
  const monthlyMap: Record<string, number> = {}
  for (const t of closed) {
    const month = t.closed_at?.slice(0, 7) ?? 'N/A'
    monthlyMap[month] = (monthlyMap[month] ?? 0) + (t.pnl_usd ?? 0)
  }
  const monthly = Object.entries(monthlyMap)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([month, pnl]) => ({ month, pnl: Math.round(pnl * 100) / 100 }))

  // Error categories from reviews
  const errorMap: Record<string, number> = {}
  for (const r of reviews ?? []) {
    if (r.error_category) {
      errorMap[r.error_category] = (errorMap[r.error_category] ?? 0) + 1
    }
  }
  const errors = Object.entries(errorMap)
    .sort(([, a], [, b]) => b - a)
    .map(([category, count]) => ({ category, count }))

  // Average scores from AI reviews (7 dimensions)
  const scoreFields = ['score_estrutura','score_timing','score_indicadores','score_macro','score_risco','score_execucao','score_disciplina'] as const
  const scoreTotals: Record<string, number> = {}
  let reviewCount = 0
  for (const r of reviews ?? []) {
    if (r.score_estrutura == null) continue
    reviewCount++
    for (const f of scoreFields) scoreTotals[f] = (scoreTotals[f] ?? 0) + (r[f] ?? 0)
  }
  const avgScores = reviewCount > 0
    ? scoreFields.map(f => ({
        dimension: f.replace('score_', '').replace('_', ' '),
        score: Math.round((scoreTotals[f] / reviewCount) * 10) / 10,
      }))
    : []

  // Process class breakdown
  const processMap: Record<string, number> = {}
  for (const r of reviews ?? []) {
    if (r.process_class) processMap[r.process_class] = (processMap[r.process_class] ?? 0) + 1
  }

  // Recent rules generated by AI
  const rules = (reviews ?? [])
    .filter((r: any) => r.new_rule)
    .slice(0, 5)
    .map((r: any) => ({ rule: r.new_rule, reviewed_at: r.reviewed_at }))

  // Summary stats
  const isWin   = (t: any) => t.pnl_usd != null ? t.pnl_usd > 0 : (t.pnl_pct ?? 0) > 0
  const winners  = closed.filter(isWin)
  const losers   = closed.filter(t => !isWin(t))
  const totalPnl = closed.reduce((s, t) => s + (t.pnl_usd ?? 0), 0)
  const best     = closed.length ? closed.reduce((b, t) => (t.pnl_usd ?? 0) > (b.pnl_usd ?? 0) ? t : b) : null
  const worst    = closed.length ? closed.reduce((w, t) => (t.pnl_usd ?? 0) < (w.pnl_usd ?? 0) ? t : w) : null
  const avgWin   = winners.length ? winners.reduce((s, t) => s + (t.pnl_usd ?? 0), 0) / winners.length : 0
  const avgLoss  = losers.length  ? losers.reduce((s, t)  => s + (t.pnl_usd ?? 0), 0) / losers.length  : 0

  // ── Métricas avançadas ─────────────────────────────────────────────────────

  // Max Drawdown — pior queda pico→fundo da equity curve
  let peak = 0; let maxDD = 0; let cumPnl = 0
  for (const t of closed) {
    cumPnl += t.pnl_usd ?? 0
    if (cumPnl > peak) peak = cumPnl
    const dd = peak - cumPnl
    if (dd > maxDD) maxDD = dd
  }
  const maxDrawdownPct = peak > 0 ? (maxDD / peak) * 100 : 0

  // Streak atual — sequência de wins ou losses no fim da lista
  let streak = 0; let streakType: 'win' | 'loss' | null = null
  for (let i = closed.length - 1; i >= 0; i--) {
    const w = isWin(closed[i])
    if (i === closed.length - 1) { streakType = w ? 'win' : 'loss'; streak = 1 }
    else if ((streakType === 'win' && w) || (streakType === 'loss' && !w)) streak++
    else break
  }

  // Profit Factor — gross win / gross loss
  const grossWin  = winners.reduce((s, t) => s + (t.pnl_usd ?? 0), 0)
  const grossLoss = Math.abs(losers.reduce((s, t) => s + (t.pnl_usd ?? 0), 0))
  const profitFactor = grossLoss > 0 ? Math.round((grossWin / grossLoss) * 100) / 100 : null

  // Recovery Factor — totalPnl / maxDrawdown
  const recoveryFactor = maxDD > 0 ? Math.round((totalPnl / maxDD) * 100) / 100 : null

  // Tempo médio de trade (dias)
  const holdingDays = closed
    .filter(t => t.opened_at && t.closed_at)
    .map(t => {
      const diff = new Date(t.closed_at).getTime() - new Date(t.opened_at).getTime()
      return diff / (1000 * 3600 * 24)
    })
  const avgHoldingDays = holdingDays.length
    ? Math.round(holdingDays.reduce((s, d) => s + d, 0) / holdingDays.length * 10) / 10
    : null

  // Melhor e pior streak histórico
  let bestStreak = 0; let worstStreak = 0
  let curW = 0; let curL = 0
  for (const t of closed) {
    if (isWin(t)) { curW++; curL = 0 } else { curL++; curW = 0 }
    if (curW > bestStreak)  bestStreak  = curW
    if (curL > worstStreak) worstStreak = curL
  }

  return NextResponse.json({
    equity, monthly, errors,
    perf: perf ?? [],
    avgScores,
    processMap,
    rules,
    summary: {
      total:    closed.length,
      winners:  winners.length,
      losers:   losers.length,
      winrate:  closed.length ? (winners.length / closed.length) * 100 : 0,
      totalPnl: Math.round(totalPnl * 100) / 100,
      avgWin:   Math.round(avgWin * 100) / 100,
      avgLoss:  Math.round(avgLoss * 100) / 100,
      best:     best  ? { asset: best.asset,  pnl: best.pnl_usd  } : null,
      worst:    worst ? { asset: worst.asset, pnl: worst.pnl_usd } : null,
    },
    risk: {
      maxDrawdown:     Math.round(maxDD * 100) / 100,
      maxDrawdownPct:  Math.round(maxDrawdownPct * 10) / 10,
      profitFactor,
      recoveryFactor,
      avgHoldingDays,
      streak,
      streakType,
      bestStreak,
      worstStreak,
    },
  })
}
